### ISSUE TITLE
Codigo

### ISSUE THREAD

**Issue by Blackgarden** [terceranexus6/CampusInWatch#1]
Alguna idea sobre como podria ser el codigo para la aplicacion? O donde podriamos buscar alguna referencia? Sea codigo o metacodigo, esto se acerca gente.

**Comment by Espectro123** [comment]
Tenemos que encontrar las bibliotecas y su documentacion. Voy a ello.... volvere

**Comment by cpu82** [comment]
Ya os he enviado via mail el código fuente para trabajar.
