### ISSUE TITLE
Interfaz

### ISSUE THREAD

**Issue by Blackgarden** [terceranexus6/CampusInWatch#2]
Veamos, la idea es que la interfaz sea sencilla (al fin y al cabo, es un pulsometro), alguna idea?

**Comment by Espectro123** [comment]
La pantalla es de 240x240 voy a intenetar hacerla en java y ponerle algun que otro boton para que nos de una vision de la app.

**Comment by Blackgarden** [comment]
Si alguien tiene alguna idea que sustituya la animacion (al menos temporalmente) que lo ponga por aqui y me encargo de implementarla...
Incluso he barajado la posibilidad de quitar la pantalla de loading, que tenga solo dos pantallas: la de inicio y la del resultado con sus correspondientes complementos. 
Lo dicho, ideas, opiniones o cualquier cosa relacionada, ayuda mucho.

**Comment by cpu82** [comment]
Esto va progresando... podéis ver los cambios https://github.com/terceranexus6/CampusInWatch/commit/2a819d86d760f1f90529dc72c921b9265f94e68b
