### ISSUE TITLE
links utiles

### ISSUE THREAD

**Issue by terceranexus6** [terceranexus6/CampusInWatch#3]
www.androidsnippets.com
www.aprendeandroid.com

http://developer.android.com/guide/index.html
http://elbauldelprogramador.com/fundamentos-programacion-android/
http://monillo007.blogspot.com.es/2013/04/conceptos-basicos-de-programacion-para.html

http://www.google.com/design/spec/material-design/introduction.html
http://www.elandroidelibre.com/2014/02/aprende-android-en-20-conceptos-empezando-a-programar-para-android.html

http://www.sgoliver.net/blog/curso-de-programacion-android/indice-de-contenidos/

http://appinventor.mit.edu/explore/

**Comment by cpu82** [comment]
Android Button Selector tutorial with example:
http://www.compiletimeerror.com/2014/03/android-button-selector-tutorial-with.html
